-- Generated by reascript-mcp: create_midi_item
reaper.Undo_BeginBlock()

local track = reaper.GetTrack(0, 0)
if track == nil then error("Track index 0 not found") end

local item = reaper.CreateNewMIDIItemInProj(track, 0.0, 4.0, false)
local take = reaper.GetActiveTake(item)
if take == nil then error("Could not get active MIDI take") end

local notes = {
  {pitch=60, start_qn=0, end_qn=1, velocity=96, channel=0},
  {pitch=64, start_qn=1, end_qn=2, velocity=90, channel=0},
  {pitch=67, start_qn=2, end_qn=3, velocity=88, channel=0}
}

for _, note in ipairs(notes) do
  local start_ppq = reaper.MIDI_GetPPQPosFromProjQN(take, note.start_qn)
  local end_ppq = reaper.MIDI_GetPPQPosFromProjQN(take, note.end_qn)
  reaper.MIDI_InsertNote(take, false, false, start_ppq, end_ppq, note.channel, note.pitch, note.velocity, true)
end

reaper.MIDI_Sort(take)
reaper.UpdateArrange()
reaper.Undo_EndBlock("Create MIDI item from reascript-mcp", -1)
