-- Generated by reascript-mcp: list_tracks
local output_path = [[/Users/craiglawton/Hacking/reascript-mcp/generated_reascripts/tracks.json]]
local track_count = reaper.CountTracks(0)
local rows = {}

for i = 0, track_count - 1 do
  local track = reaper.GetTrack(0, i)
  local ok, name = reaper.GetSetMediaTrackInfo_String(track, "P_NAME", "", false)
  if name == "" then name = "Track " .. tostring(i + 1) end
  rows[#rows + 1] = string.format('{"index":%d,"name":%q}', i, name)
end

local file = assert(io.open(output_path, "w"))
file:write('{"tracks":[' .. table.concat(rows, ',') .. ']}')
file:close()
reaper.ShowConsoleMsg("Wrote track report to " .. output_path .. "\n")
