"""Generate Lua ReaScripts for common project-control actions."""

from __future__ import annotations

from pathlib import Path
from typing import Any


DEFAULT_SCRIPT_DIR = Path("generated_reascripts")


def generate_reascript(action: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
    """Return a ReaScript Lua script for a supported action.

    This tool generates scripts for execution inside Reaper. It does not require
    Reaper at generation time, making it testable and safe for LLM workflows.
    """

    params = params or {}
    if action == "list_tracks":
        return _list_tracks(params)
    if action == "create_midi_item":
        return _create_midi_item(params)
    raise ValueError(f"Unsupported ReaScript action: {action}")


def _list_tracks(params: dict[str, Any]) -> dict[str, Any]:
    output_path = params.get("output_path", "tracks.json")
    script = f'''-- Generated by reascript-mcp: list_tracks
local output_path = [[{output_path}]]
local track_count = reaper.CountTracks(0)
local rows = {{}}

for i = 0, track_count - 1 do
  local track = reaper.GetTrack(0, i)
  local ok, name = reaper.GetSetMediaTrackInfo_String(track, "P_NAME", "", false)
  if name == "" then name = "Track " .. tostring(i + 1) end
  rows[#rows + 1] = string.format('{{"index":%d,"name":%q}}', i, name)
end

local file = assert(io.open(output_path, "w"))
file:write('{{"tracks":[' .. table.concat(rows, ',') .. ']}}')
file:close()
reaper.ShowConsoleMsg("Wrote track report to " .. output_path .. "\\n")
'''
    return {
        "action": "list_tracks",
        "language": "lua",
        "script_path": str(DEFAULT_SCRIPT_DIR / "list_tracks.lua"),
        "script": script,
        "summary": "Generated Lua ReaScript to list tracks and write JSON state readback.",
    }


def _create_midi_item(params: dict[str, Any]) -> dict[str, Any]:
    track_index = _require_int(params, "track_index", minimum=0)
    start_qn = _require_number(params, "start_qn", minimum=0)
    end_qn = _require_number(params, "end_qn", minimum=start_qn)
    notes = params.get("notes")
    if not isinstance(notes, list) or not notes:
        raise ValueError("notes must be a non-empty list")

    rendered_notes: list[str] = []
    for note in notes:
        if not isinstance(note, dict):
            raise ValueError("each note must be an object")
        pitch = _require_int(note, "pitch", minimum=0, maximum=127)
        note_start = _require_number(note, "start_qn", minimum=start_qn)
        note_end = _require_number(note, "end_qn", minimum=note_start)
        velocity = int(note.get("velocity", 96))
        if not 1 <= velocity <= 127:
            raise ValueError("velocity must be between 1 and 127")
        channel = int(note.get("channel", 0))
        if not 0 <= channel <= 15:
            raise ValueError("channel must be between 0 and 15")
        rendered_notes.append(
            "  {pitch=%d, start_qn=%s, end_qn=%s, velocity=%d, channel=%d}"
            % (pitch, _lua_number(note_start), _lua_number(note_end), velocity, channel)
        )

    note_table = ",\n".join(rendered_notes)
    script = f'''-- Generated by reascript-mcp: create_midi_item
reaper.Undo_BeginBlock()

local track = reaper.GetTrack(0, {track_index})
if track == nil then error("Track index {track_index} not found") end

local item = reaper.CreateNewMIDIItemInProj(track, {start_qn}, {end_qn}, false)
local take = reaper.GetActiveTake(item)
if take == nil then error("Could not get active MIDI take") end

local notes = {{
{note_table}
}}

for _, note in ipairs(notes) do
  local start_ppq = reaper.MIDI_GetPPQPosFromProjQN(take, note.start_qn)
  local end_ppq = reaper.MIDI_GetPPQPosFromProjQN(take, note.end_qn)
  reaper.MIDI_InsertNote(take, false, false, start_ppq, end_ppq, note.channel, note.pitch, note.velocity, true)
end

reaper.MIDI_Sort(take)
reaper.UpdateArrange()
reaper.Undo_EndBlock("Create MIDI item from reascript-mcp", -1)
'''
    return {
        "action": "create_midi_item",
        "language": "lua",
        "script_path": str(DEFAULT_SCRIPT_DIR / "create_midi_item.lua"),
        "script": script,
        "summary": f"Generated Lua ReaScript to create a MIDI item with {len(notes)} MIDI notes.",
    }


def _require_int(data: dict[str, Any], key: str, *, minimum: int, maximum: int | None = None) -> int:
    if key not in data or not isinstance(data[key], int):
        raise ValueError(f"{key} must be an integer")
    value = data[key]
    if value < minimum or (maximum is not None and value > maximum):
        raise ValueError(f"{key} must be between {minimum} and {maximum if maximum is not None else '∞'}")
    return value


def _require_number(data: dict[str, Any], key: str, *, minimum: float) -> float:
    if key not in data or not isinstance(data[key], (int, float)):
        raise ValueError(f"{key} must be a number")
    value = float(data[key])
    if value < minimum:
        raise ValueError(f"{key} must be >= {minimum:g}")
    return value


def _lua_number(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else str(value)
