"""Generate Lua ReaScripts for common project-control actions."""

from __future__ import annotations

from pathlib import Path
from typing import Any


DEFAULT_SCRIPT_DIR = Path("generated_reascripts")


def generate_reascript(action: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
    """Return a ReaScript Lua script for a supported action.

    This tool generates scripts for execution inside Reaper. It does not require
    Reaper at generation time, making it testable and safe for LLM workflows.
    """

    params = params or {}
    if action == "list_tracks":
        return _list_tracks(params)
    if action == "create_midi_item":
        return _create_midi_item(params)
    if action == "read_project_state":
        return _read_project_state(params)
    if action == "create_track":
        return _create_track(params)
    if action == "import_midi_file":
        return _import_midi_file(params)
    raise ValueError(f"Unsupported ReaScript action: {action}")


def _list_tracks(params: dict[str, Any]) -> dict[str, Any]:
    output_path = params.get("output_path", "tracks.json")
    script = f'''-- Generated by reascript-mcp: list_tracks
local output_path = [[{output_path}]]
local track_count = reaper.CountTracks(0)
local rows = {{}}

for i = 0, track_count - 1 do
  local track = reaper.GetTrack(0, i)
  local ok, name = reaper.GetSetMediaTrackInfo_String(track, "P_NAME", "", false)
  if name == "" then name = "Track " .. tostring(i + 1) end
  rows[#rows + 1] = string.format('{{"index":%d,"name":%q}}', i, name)
end

local file = assert(io.open(output_path, "w"))
file:write('{{"tracks":[' .. table.concat(rows, ',') .. ']}}')
file:close()
reaper.ShowConsoleMsg("Wrote track report to " .. output_path .. "\\n")
'''
    return {
        "action": "list_tracks",
        "language": "lua",
        "script_path": str(DEFAULT_SCRIPT_DIR / "list_tracks.lua"),
        "script": script,
        "summary": "Generated Lua ReaScript to list tracks and write JSON state readback.",
    }


def _create_track(params: dict[str, Any]) -> dict[str, Any]:
    name = _require_non_empty_string(params, "name")
    index = params.get("index")
    if index is None:
        index_expr = "reaper.CountTracks(0)"
    elif isinstance(index, int) and index >= 0:
        index_expr = str(index)
    else:
        raise ValueError("index must be a non-negative integer when provided")

    script = f'''-- Generated by reascript-mcp: create_track
reaper.Undo_BeginBlock()
local insert_index = {index_expr}
reaper.InsertTrackAtIndex({index_expr}, true)
local track = reaper.GetTrack(0, insert_index)
if track == nil then error("Could not create track at index " .. tostring(insert_index)) end
reaper.GetSetMediaTrackInfo_String(track, "P_NAME", {_lua_string(name)}, true)
reaper.TrackList_AdjustWindows(false)
reaper.UpdateArrange()
reaper.Undo_EndBlock("Create track from reascript-mcp", -1)
'''
    return {
        "action": "create_track",
        "language": "lua",
        "script_path": str(DEFAULT_SCRIPT_DIR / "create_track.lua"),
        "script": script,
        "summary": f"Generated Lua ReaScript to create track named {name!r}.",
    }


def _import_midi_file(params: dict[str, Any]) -> dict[str, Any]:
    track_index = _require_int(params, "track_index", minimum=0)
    midi_file_path = _require_non_empty_string(params, "midi_file_path")
    position_qn = params.get("position_qn", 0)
    if not isinstance(position_qn, (int, float)) or position_qn < 0:
        raise ValueError("position_qn must be a non-negative number")
    position_qn = float(position_qn)

    script = f'''-- Generated by reascript-mcp: import_midi_file
reaper.Undo_BeginBlock()

local track_index = {track_index}
local midi_file_path = [[{midi_file_path}]]
local position_qn = {_lua_number(position_qn)}

local track = reaper.GetTrack(0, track_index)
if track == nil then error("Track index " .. tostring(track_index) .. " not found") end

-- Convert QN to time in seconds and set edit cursor
local position_time = reaper.TimeMap_QNToTime(position_qn)
reaper.SetEditCurPos(position_time, false, false)

-- Select the target track so InsertMedia places the item there
reaper.SetOnlyTrackSelected(track)

-- Insert the MIDI file at the edit cursor
local retval, inserted_item = reaper.InsertMedia(midi_file_path, 0)

if not retval then
  reaper.ShowConsoleMsg("Failed to import MIDI file: " .. midi_file_path .. "\\n")
  reaper.Undo_EndBlock("Import MIDI file (failed)", -1)
  return
end

reaper.ShowConsoleMsg("Imported MIDI file: " .. midi_file_path .. " onto track " .. tostring(track_index) .. "\\n")
reaper.UpdateArrange()
reaper.Undo_EndBlock("Import MIDI file from reascript-mcp", -1)
'''
    return {
        "action": "import_midi_file",
        "language": "lua",
        "script_path": str(DEFAULT_SCRIPT_DIR / "import_midi_file.lua"),
        "script": script,
        "summary": f"Generated Lua ReaScript to import MIDI file {midi_file_path!r} onto track {track_index} at position {position_qn} QN.",
    }


def _read_project_state(params: dict[str, Any]) -> dict[str, Any]:
    output_path = params.get("output_path", "project_state.json")
    script = f'''-- Generated by reascript-mcp: read_project_state
local output_path = [[{output_path}]]

local function json_escape(value)
  value = tostring(value or "")
  value = value:gsub('\\\\', '\\\\\\\\')
  value = value:gsub('"', '\\\\"')
  value = value:gsub('\\n', '\\\\n')
  value = value:gsub('\\r', '\\\\r')
  value = value:gsub('\\t', '\\\\t')
  return '"' .. value .. '"'
end

local function bool_json(value)
  if value then return "true" else return "false" end
end

local function source_type_for_item(item)
  local take = reaper.GetActiveTake(item)
  if take == nil then return "UNKNOWN" end
  if reaper.TakeIsMIDI(take) then return "MIDI" end
  local source = reaper.GetMediaItemTake_Source(take)
  if source == nil then return "UNKNOWN" end
  local source_type = reaper.GetMediaSourceType(source, "")
  if source_type ~= nil and source_type ~= "" then return source_type end
  return "UNKNOWN"
end

local track_count = reaper.CountTracks(0)
local track_rows = {{}}

for i = 0, track_count - 1 do
  local track = reaper.GetTrack(0, i)
  local ok, name = reaper.GetSetMediaTrackInfo_String(track, "P_NAME", "", false)
  if name == "" then name = "Track " .. tostring(i + 1) end

  local fx_rows = {{}}
  local fx_count = reaper.TrackFX_GetCount(track)
  for fx = 0, fx_count - 1 do
    local ok_fx, fx_name = reaper.TrackFX_GetFXName(track, fx, "")
    fx_rows[#fx_rows + 1] = string.format('{{"index":%d,"name":%s}}', fx, json_escape(fx_name))
  end

  local item_rows = {{}}
  local item_count = reaper.CountTrackMediaItems(track)
  for item_index = 0, item_count - 1 do
    local item = reaper.GetTrackMediaItem(track, item_index)
    local position = reaper.GetMediaItemInfo_Value(item, "D_POSITION")
    local length = reaper.GetMediaItemInfo_Value(item, "D_LENGTH")
    local muted = reaper.GetMediaItemInfo_Value(item, "B_MUTE") == 1
    local source_type = source_type_for_item(item)
    item_rows[#item_rows + 1] = string.format(
      '{{"index":%d,"position":%.9g,"length":%.9g,"muted":%s,"source_type":%s}}',
      item_index,
      position,
      length,
      bool_json(muted),
      json_escape(source_type)
    )
  end

  track_rows[#track_rows + 1] = string.format(
    '{{"index":%d,"name":%s,"fx":[%s],"items":[%s]}}',
    i,
    json_escape(name),
    table.concat(fx_rows, ','),
    table.concat(item_rows, ',')
  )
end

local marker_rows = {{}}
local marker_count, region_count = reaper.CountProjectMarkers(0)
local total_markers = marker_count + region_count
for marker_index = 0, total_markers - 1 do
  local retval, is_region, position, region_end, name, marker_id = reaper.EnumProjectMarkers3(0, marker_index)
  if retval ~= 0 then
    marker_rows[#marker_rows + 1] = string.format(
      '{{"index":%d,"id":%d,"name":%s,"is_region":%s,"position":%.9g,"end":%.9g}}',
      marker_index,
      marker_id,
      json_escape(name),
      bool_json(is_region),
      position,
      region_end
    )
  end
end

local tempo = reaper.Master_GetTempo()
local file = assert(io.open(output_path, "w"))
file:write(string.format(
  '{{"tempo":%.9g,"track_count":%d,"marker_count":%d,"region_count":%d,"tracks":[%s],"markers":[%s]}}',
  tempo,
  track_count,
  marker_count,
  region_count,
  table.concat(track_rows, ','),
  table.concat(marker_rows, ',')
))
file:close()
reaper.ShowConsoleMsg("Wrote project state to " .. output_path .. "\\n")
'''
    return {
        "action": "read_project_state",
        "language": "lua",
        "script_path": str(DEFAULT_SCRIPT_DIR / "read_project_state.lua"),
        "script": script,
        "summary": "Generated Lua ReaScript to read project state including tracks, FX, items, and markers.",
    }


def _create_midi_item(params: dict[str, Any]) -> dict[str, Any]:
    track_index = _require_int(params, "track_index", minimum=0)
    start_qn = _require_number(params, "start_qn", minimum=0)
    end_qn = _require_number(params, "end_qn", minimum=start_qn)
    notes = params.get("notes")
    if not isinstance(notes, list) or not notes:
        raise ValueError("notes must be a non-empty list")

    rendered_notes: list[str] = []
    for note in notes:
        if not isinstance(note, dict):
            raise ValueError("each note must be an object")
        pitch = _require_int(note, "pitch", minimum=0, maximum=127)
        note_start = _require_number(note, "start_qn", minimum=start_qn)
        note_end = _require_number(note, "end_qn", minimum=note_start)
        velocity = int(note.get("velocity", 96))
        if not 1 <= velocity <= 127:
            raise ValueError("velocity must be between 1 and 127")
        channel = int(note.get("channel", 0))
        if not 0 <= channel <= 15:
            raise ValueError("channel must be between 0 and 15")
        rendered_notes.append(
            "  {pitch=%d, start_qn=%s, end_qn=%s, velocity=%d, channel=%d}"
            % (pitch, _lua_number(note_start), _lua_number(note_end), velocity, channel)
        )

    note_table = ",\n".join(rendered_notes)
    script = f'''-- Generated by reascript-mcp: create_midi_item
reaper.Undo_BeginBlock()

local track = reaper.GetTrack(0, {track_index})
if track == nil then error("Track index {track_index} not found") end

local item = reaper.CreateNewMIDIItemInProj(track, {start_qn}, {end_qn}, false)
local take = reaper.GetActiveTake(item)
if take == nil then error("Could not get active MIDI take") end

local notes = {{
{note_table}
}}

for _, note in ipairs(notes) do
  local start_ppq = reaper.MIDI_GetPPQPosFromProjQN(take, note.start_qn)
  local end_ppq = reaper.MIDI_GetPPQPosFromProjQN(take, note.end_qn)
  reaper.MIDI_InsertNote(take, false, false, start_ppq, end_ppq, note.channel, note.pitch, note.velocity, true)
end

reaper.MIDI_Sort(take)
reaper.UpdateArrange()
reaper.Undo_EndBlock("Create MIDI item from reascript-mcp", -1)
'''
    return {
        "action": "create_midi_item",
        "language": "lua",
        "script_path": str(DEFAULT_SCRIPT_DIR / "create_midi_item.lua"),
        "script": script,
        "summary": f"Generated Lua ReaScript to create a MIDI item with {len(notes)} MIDI notes.",
    }


def _require_int(data: dict[str, Any], key: str, *, minimum: int, maximum: int | None = None) -> int:
    if key not in data or not isinstance(data[key], int):
        raise ValueError(f"{key} must be an integer")
    value = data[key]
    if value < minimum or (maximum is not None and value > maximum):
        raise ValueError(f"{key} must be between {minimum} and {maximum if maximum is not None else '∞'}")
    return value


def _require_number(data: dict[str, Any], key: str, *, minimum: float) -> float:
    if key not in data or not isinstance(data[key], (int, float)):
        raise ValueError(f"{key} must be a number")
    value = float(data[key])
    if value < minimum:
        raise ValueError(f"{key} must be >= {minimum:g}")
    return value


def _require_non_empty_string(data: dict[str, Any], key: str) -> str:
    value = data.get(key)
    if not isinstance(value, str) or value.strip() == "":
        raise ValueError(f"{key} must be a non-empty string")
    return value


def _lua_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def _lua_number(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else str(value)
